version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: Nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/laravel
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    container_name: PHP
    build:
      context: .
      dockerfile: php/Php.Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=laravel-test
    volumes:
      - ./src:/var/www/laravel
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  mysql:
    image: mysql:8
    container_name: MySql
    restart: unless-stopped
    tty: true
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    container_name: Redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server

volumes:
  dbdata:
    driver: local